# -*- coding: utf-8 -*-
"""Cropyeild .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MebjeIgqGvFyeI3EaCDkqXQ-xHoShExX
"""

import pandas as pd
from sklearn.linear_model import LinearRegression

cyf=pd.read_csv('/content/crop_yield_fertilizer_300.csv')

cyf.head()

cyf.isnull().sum()

cyf.info()

cyf.dropna(inplace=True)

from sklearn.preprocessing import LabelEncoder

LE=LabelEncoder()

cyf['crop_new']=LE.fit_transform(cyf['Crop'])

cyf.tail()

LR=LinearRegression()

a=cyf[['ID','Temperature (°C)','Rainfall (mm)','Soil pH','Nitrogen (N)','Phosphorus (P)','Potassium (K)','crop_new']]

b=cyf['Yield (tons/ha)']

LR.fit(a,b)

LR.predict([[296,20.1,1618,5.5,61,52,54,5]])