# -*- coding: utf-8 -*-
"""K-customer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sxwkm6lyJGWHaDpKvdpUmZNSQyuLV3cY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

csd=pd.read_excel('/content/Mall_Customers.xlsx')

csd.head()

csd.isnull().sum()

csd.shape

csd.info()

x=csd.iloc[:,[3,4]].values

print(x)

wcss = []

for i in range(1,11):
  Kmeans = KMeans(n_clusters = i, init = 'k-means++',random_state=42)
  Kmeans.fit(x)

  wcss.append(Kmeans.inertia_)

sns.set()
plt.plot(range(1,11),wcss)
plt.title('The Elbow graph')
plt.xlabel('Number of clusters')
plt.ylabel('wcss')
plt.show()

K=KMeans(n_clusters=5,init='k-means++',random_state=0)
y=K.fit_predict(x)

print(y)

plt.figure(figsize=(8,8))
plt.scatter(x[y==0,0],x[y==0,1],s=50,c='green',label='cluster1')
plt.scatter(x[y==1,0],x[y==1,1],s=50,c='red',label='cluster2')
plt.scatter(x[y==2,0],x[y==2,1],s=50,c='yellow',label='cluster3')
plt.scatter(x[y==3,0],x[y==3,1],s=50,c='blue',label='cluster4')
plt.scatter(x[y==4,0],x[y==4,1],s=50,c='black',label='cluster5')
plt.scatter(K.cluster_centers_[:,0],K.cluster_centers_[:,1],s=300,c='cyan',label='centroids')
plt.title('Clusters of customers')
plt.show()