# -*- coding: utf-8 -*-
"""K-NN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9ZjtpjCq9kFCXkcQR42OYrLNzfgLf7k
"""

import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from matplotlib import pyplot as plt

data={
    'BP':[120,130,140,150,160,170,180,190,200,210],
    'Cholesterol':[200,220,240,260,280,300,320,340,360,380],
    'HeartRisk':[0,0,0,0,1,1,1,1,1,1]
}

df=pd.DataFrame(data)

X=df[['BP','Cholesterol']]
Y=df['HeartRisk']

k=3
knn=KNeighborsClassifier(n_neighbors=k)
knn.fit(X,Y)

new_data=np.array([[210,250]])
prediction=knn.predict(new_data)
if prediction==0:
  print("No Risk")
else:
  print("At Risk")