# -*- coding: utf-8 -*-
"""SALARY .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16I_2AQTtRgire4LvmWSzsMc3WLNwsDg0
"""

import pandas as pd
from sklearn.linear_model import LinearRegression

saldf=pd.read_csv('/content/Salary Data.csv')

saldf.head()

saldf.isnull().sum()

saldf.info()

saldf.dropna(inplace=True)

saldf.info()

saldf.isnull().sum()

from sklearn.preprocessing import LabelEncoder

LE=LabelEncoder()

saldf ["Edu_n"]=LE.fit_transform(saldf["Education Level"])

saldf.tail()

LE1=LabelEncoder()

saldf["gen"]=LE1.fit_transform(saldf["Gender"])

saldf.head()

a=saldf[['Age','Years of Experience','Edu_n','gen']]

b=saldf['Salary']

LR=LinearRegression()

LR.fit(a,b)

LR.predict([[30,5,1,0]])