# -*- coding: utf-8 -*-
"""stroke.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B9z7m_Sc5MkY1Sgzu7eVf0jhUOTvXKbJ
"""

import pandas as pd
from sklearn.linear_model import LinearRegression

hds=pd.read_csv('/content/healthcare-dataset-stroke-data.csv')

hds.head()

hds.isnull().sum()

hds.info()

hds.dropna(inplace=True)

hds.isnull().sum()

hds.info()

from sklearn.preprocessing import LabelEncoder

LE=LabelEncoder()

hds['gen']=LE.fit_transform(hds['gender'])

hds.tail()

LE1=LabelEncoder()

hds['WT']=LE1.fit_transform(hds['work_type'])

hds.head()

LE2=LabelEncoder()

hds['em']=LE2.fit_transform(hds['ever_married'])

hds.tail()

LE3=LabelEncoder()

hds['rt']=LE3.fit_transform(hds['Residence_type'])

hds.head()

LE4=LabelEncoder()

hds['ss']=LE4.fit_transform(hds['smoking_status'])

hds.head()

LR=LinearRegression()

a=hds[['id','age','hypertension','heart_disease','avg_glucose_level','bmi','gen','WT','em','rt','ss']]

b=hds['stroke']

LR.fit(a,b)

LR.predict([[67.0,0,1,228.69,36.6,1,1,2,1,1,1]])