# -*- coding: utf-8 -*-
"""Student mark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S0-GfiCOyXcP_zjeS9qw0Jqoj49phUhX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

sdm=pd.read_csv('/content/Student_Marks.csv')

sdm.info()

sdm.isnull().sum()

sdm.shape

x=sdm.iloc[:,[1,2]].values

print(x)

wcss=[]
for i in range(1,11):
  Kmeans = KMeans(n_clusters=i,init='k-means++',random_state=55)
  Kmeans.fit(x)
  wcss.append(Kmeans.inertia_)

sns.set()
plt.plot(range(1,11),wcss)
plt.title('the student mark')
plt.xlabel('time of studies')
plt.ylabel('marks')
plt.show()